version: "3.8"

services:
  user_app:
    build: 
      context: ./User_service
      dockerfile: Dockerfile
    environment:
      DB_HOST: "user_db"
      DB_NAME: "users"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    ports:
      - "3000:3000"
    depends_on:
      - user_db
    links:
      - user_db
    networks:
      - user_net
  user_db:
    image: postgres
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - user_net
networks:
  user_net:
    driver: bridge